# Generated by Django 3.2.13 on 2023-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
