# Generated by Django 3.2.13 on 2023-12-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0003_auto_20231207_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='Register',
        ),
    ]
