# Generated by Django 3.2.13 on 2023-12-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0004_rename_registerform_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
