# Generated by Django 3.2.13 on 2023-12-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0005_rename_register_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.username'),
        ),
    ]
