# Generated by Django 3.2.13 on 2023-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0006_auto_20231209_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
