# Generated by Django 3.2.13 on 2023-12-11 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0009_auto_20231210_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='gifts',
            name='gift',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.myuser'),
        ),
    ]
